Add property to allow turn on KMS-SSE encryption when putting data in S3
jgroups-extras/jgroups-aws pull request #225
Opened 2022-09-22 09:07 UTC by haroldpirum

Add property to allow turn on KMS-SSE encryption when putting data in S3 with the given kms id.  Update README.md

2022-10-06 08:12 UTC, haroldpirum commented
Hi @rhusar please could you help review this.

Thanks,
Harold

2022-10-13 19:20 UTC, rhusar commented
Thanks @haroldpirum – I did review the code, I think this generally looks good, just need to run the tests to verify there isn't anything going awry. Just some nitpics.

2022-10-13 19:23 UTC, rhusar requested changes

2022-10-13 19:23 UTC, rhusar commented on src/main/java/org/jgroups/protocols/aws/S3_PING.java
> +    @Property(description="Use kms encryption with s3 with the given kms key (optionally - enables KMS Server side encryption (SSE-KMS) using the given kms key", exposeAsManagedAttribute=false)
This is missing closing `)`.

2022-10-13 19:23 UTC, rhusar commented on src/main/java/org/jgroups/protocols/aws/S3_PING.java
> +    protected SSEAwsKeyManagementParams encryptionParams = null;
The initialization of a field is redundant as per JLS.

2022-10-19 08:26 UTC, haroldb1 commented
hi @rhusar could you help review again please.
Thanks!

2022-11-07 14:34 UTC, haroldpirum commented
hi @rhusar i believe i added all the requested changes, though the review still says changes requested.  Is it possible to recheck please.

Thanks,
Harold

2022-11-08 11:40 UTC, rhusar commented
@haroldpirum Sorry for the delay, we needed to clear up a few things before really opening the branch for further development. Will review and merge this week.

2023-01-09 16:16 UTC, haroldpirum commented
Hi @rhusar are we in a position to merge this please?

2023-03-23 14:43 UTC, ioannoapirum commented
@rhusar any chance this could be looked at? It would benefit our project.

2023-03-23 14:45 UTC, rhusar commented
@haroldpirum @ioannoapirum Sorry for the delay I will try to review by tomorrow.

2023-03-25 21:12 UTC, rhusar approved these changes
The changes look good now. Just to mention - anyone looking at this feature - this is a *server-side* encryption. Also, Amazon S3 applies server-side encryption with Amazon S3 managed keys (SSE-S3) as the base level of encryption for every bucket in Amazon S3 since start of 2023.

2023-03-25 21:12 UTC, merged

2023-03-25 21:12 UTC, rhusar commented
Thanks @haroldpirum!

2023-03-25 21:24 UTC, rhusar commented
Oh, would a release be helpful @haroldpirum @ioannoapirum ?